using System.Text.Json;
using System.Text.Json.Serialization;
using Means.Core;
using Means.Endpoints.Console;

namespace Means.Serialization;

[JsonSourceGenerationOptions(JsonSerializerDefaults.Web)]
[JsonSerializable(typeof(LoginRequest))]
[JsonSerializable(typeof(SessionResponse))]
[JsonSerializable(typeof(OverviewResponse))]
[JsonSerializable(typeof(DashboardStatsResponse))]
[JsonSerializable(typeof(DashboardRangeResponse))]
[JsonSerializable(typeof(DashboardCapacityResponse))]
[JsonSerializable(typeof(DashboardSummaryResponse))]
[JsonSerializable(typeof(DashboardNodesResponse))]
[JsonSerializable(typeof(DashboardPathStatusResponse))]
[JsonSerializable(typeof(DashboardHourlyMetricResponse))]
[JsonSerializable(typeof(DashboardRecentBucketResponse))]
[JsonSerializable(typeof(DashboardPoolResponse))]
[JsonSerializable(typeof(BucketSummaryResponse))]
[JsonSerializable(typeof(BackgroundTaskManagementResponse))]
[JsonSerializable(typeof(CreateBucketRequest))]
[JsonSerializable(typeof(UpdateBucketSettingsRequest))]
[JsonSerializable(typeof(BucketVersioningConsoleRequest))]
[JsonSerializable(typeof(BucketLifecycleConsoleRequest))]
[JsonSerializable(typeof(LifecycleRuleConsoleRequest))]
[JsonSerializable(typeof(PolicyRequest))]
[JsonSerializable(typeof(PolicyResponse))]
[JsonSerializable(typeof(CopyObjectConsoleRequest))]
[JsonSerializable(typeof(BatchDeleteObjectsRequest))]
[JsonSerializable(typeof(BatchDeleteObjectItem))]
[JsonSerializable(typeof(BatchDeleteResult))]
[JsonSerializable(typeof(PresignRequest))]
[JsonSerializable(typeof(PresignedTransferResponse))]
[JsonSerializable(typeof(InitiateMultipartConsoleRequest))]
[JsonSerializable(typeof(MultipartUploadConsoleResponse))]
[JsonSerializable(typeof(PresignMultipartPartRequest))]
[JsonSerializable(typeof(CompleteMultipartConsoleRequest))]
[JsonSerializable(typeof(CompletedMultipartPartConsoleRequest))]
[JsonSerializable(typeof(AbortMultipartConsoleRequest))]
[JsonSerializable(typeof(CreateAccessKeyRequest))]
[JsonSerializable(typeof(SetAccessKeyStatusRequest))]
[JsonSerializable(typeof(UpdateSystemSettingsRequest))]
[JsonSerializable(typeof(SystemSettingsResponse))]
[JsonSerializable(typeof(SaveErasureCodingProfileRequest))]
[JsonSerializable(typeof(ConsoleApiError))]
[JsonSerializable(typeof(AccessKeyInfo))]
[JsonSerializable(typeof(AccessKeySecretResult))]
[JsonSerializable(typeof(AuditEntry))]
[JsonSerializable(typeof(BackgroundTaskGroup))]
[JsonSerializable(typeof(BackgroundTaskRunRecord))]
[JsonSerializable(typeof(BackgroundTaskSnapshot))]
[JsonSerializable(typeof(BucketConsoleSummary))]
[JsonSerializable(typeof(BucketLifecycleConfiguration))]
[JsonSerializable(typeof(BucketSettings))]
[JsonSerializable(typeof(BucketUsageInfo))]
[JsonSerializable(typeof(BucketVersioningInfo))]
[JsonSerializable(typeof(ClusterDiagnostics))]
[JsonSerializable(typeof(ClusterDiagnosticsSummary))]
[JsonSerializable(typeof(ClusterInternalTransportDiagnostics))]
[JsonSerializable(typeof(CapacityAdmissionDiagnostics))]
[JsonSerializable(typeof(PlacementPolicyDiagnostics))]
[JsonSerializable(typeof(ClusterNodeInfo))]
[JsonSerializable(typeof(ClusterTopology))]
[JsonSerializable(typeof(ConsoleHourlyMetric))]
[JsonSerializable(typeof(ErasureCodingDiagnostics))]
[JsonSerializable(typeof(ErasureCodingProfile))]
[JsonSerializable(typeof(LifecycleRule))]
[JsonSerializable(typeof(ListObjectsResult))]
[JsonSerializable(typeof(ListObjectVersionsResult))]
[JsonSerializable(typeof(ListedObject))]
[JsonSerializable(typeof(ListedObjectVersion))]
[JsonSerializable(typeof(MetadataDiagnostics))]
[JsonSerializable(typeof(ObjectInfo))]
[JsonSerializable(typeof(ObjectReplicaDiagnostics))]
[JsonSerializable(typeof(ReplicaRepairQueueDiagnostics))]
[JsonSerializable(typeof(ReplicaRepairQueueItemDiagnostics))]
[JsonSerializable(typeof(ReplicaRepairQueueStatusDiagnostics))]
[JsonSerializable(typeof(StorageClusterInfo))]
[JsonSerializable(typeof(StorageDiskInfo))]
[JsonSerializable(typeof(StoragePoolInfo))]
[JsonSerializable(typeof(SystemSettings))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(IReadOnlyDictionary<string, string>))]
[JsonSerializable(typeof(IReadOnlyList<AccessKeyInfo>))]
[JsonSerializable(typeof(IReadOnlyList<AuditEntry>))]
[JsonSerializable(typeof(IReadOnlyList<BackgroundTaskGroup>))]
[JsonSerializable(typeof(IReadOnlyList<BackgroundTaskRunRecord>))]
[JsonSerializable(typeof(IReadOnlyList<BackgroundTaskSnapshot>))]
[JsonSerializable(typeof(IReadOnlyList<BucketUsageInfo>))]
[JsonSerializable(typeof(IReadOnlyList<DashboardHourlyMetricResponse>))]
[JsonSerializable(typeof(IReadOnlyList<DashboardPathStatusResponse>))]
[JsonSerializable(typeof(IReadOnlyList<DashboardPoolResponse>))]
[JsonSerializable(typeof(IReadOnlyList<DashboardRecentBucketResponse>))]
[JsonSerializable(typeof(IReadOnlyList<ErasureCodingProfile>))]
[JsonSerializable(typeof(IReadOnlyList<LifecycleRule>))]
[JsonSerializable(typeof(IReadOnlyList<ListedObject>))]
[JsonSerializable(typeof(IReadOnlyList<ListedObjectVersion>))]
[JsonSerializable(typeof(IReadOnlyList<ReplicaRepairQueueItemDiagnostics>))]
[JsonSerializable(typeof(IReadOnlyList<ReplicaRepairQueueStatusDiagnostics>))]
[JsonSerializable(typeof(IReadOnlyList<StorageDiskInfo>))]
[JsonSerializable(typeof(IReadOnlyList<StoragePoolInfo>))]
[JsonSerializable(typeof(IReadOnlyList<ClusterNodeInfo>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
internal sealed partial class MeansJsonContext : JsonSerializerContext;
